# Config port, context path
server:
  port: 9090
  servlet:
    context-path: /mobilestore

# Config database
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mobileStore
        username: root
        password: Kh12.v3@C4b5rs6ft
        driver-class-name: com.mysql.cj.jdbc.Driver
    main:
        allow-circular-references: true
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        repositories:
            enabled: true
    # Default login security
    security:
        UserEntity:
            name: admin
            password: admin123

    # Config RabbitMQ
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest

# Expose actuator endpoints
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true